### ISSUE TITLE
Wrong version output

### ISSUE THREAD

**Issue by dani** [wrouesnel/p2cli#50]
Just installed r14 (using the pre-built binary on linux-amd64). But the output of p2 --version is incorrect 
```
[dbd@laptop-103 ~]$ p2 --version
r13-4-gbc5fdbe
[dbd@laptop-103 ~]$ 
```

While not a big issue, I'd like to use this output to check if I'm running the latest version (comparing with tag_name from https://api.github.com/repos/wrouesnel/p2cli/releases/latest), and auto-update it if needed

**Comment by wrouesnel** [comment]
Closed by #52
