### ISSUE TITLE
Disable autoescape by default

### ISSUE THREAD

**Issue by estahn** [wrouesnel/p2cli#6]
my.template
```
{{ TEST }}
```

Command:
```
TEST="foo&bar" p2cli -t my.template
```

Returns:
```
foo&amp;bar
```

Expected:
```
foo&bar
```

**Comment by estahn** [comment]
The way around this behaviour is by using autoescape function:

```
{% autoescape off %}
{{ TEST }}
{% endautoescape %}
```

Thanks to https://github.com/flosch/pongo2/issues/129#issuecomment-221346740

**Comment by tushar2708** [comment]
Would like to add, that It would be really great to have auto-escaping to be off by default. Will help in cases where pongo2 is being used as a near drop-in replacement of Django/Jinja.
